apiVersion: apps/v1
kind: Deployment
metadata:
  name: stc-remodel-be
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stc-remodel-be
  template:
    metadata:
      labels:
        app: stc-remodel-be
    spec:
      containers:
        - name: stc-remodel-be
          image:  softowersolutions/stc-remodel-be:b50d7c5012be62fd0d0197f097229e2e3dfacfbc
          ports:
            - containerPort: 3000
