apiVersion: apps/v1
kind: Deployment
metadata:
  name: stc-remodel-be
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stc-remodel-be
  template:
    metadata:
      labels:
        app: stc-remodel-be
    spec:
      containers:
        - name: stc-remodel-be
          image:  softowersolutions/stc-remodel-be:356d60fba096d603f3911c44cde1eeedd706d2cb
          ports:
            - containerPort: 3000
