apiVersion: apps/v1
kind: Deployment
metadata:
  name: stc-remodel-be
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stc-remodel-be
  template:
    metadata:
      labels:
        app: stc-remodel-be
    spec:
      containers:
        - name: stc-remodel-be
          image:  softowersolutions/stc-remodel-be:87a9071344088bffc2aadf0b41553f31ab45ecf7
          ports:
            - containerPort: 3000
