apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stc-remodel-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: 13.235.16.238
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stc-remodel-ui-service
                port:
                  number: 80
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: stc-remodel-be-service
                port:
                  number: 3000
