apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stc-remodel-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: demo.transezy.com
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: stc-remodel-ui-service
                port:
                  number: 3000
          - path: /api/v1(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: stc-remodel-be-service
                port:
                  number: 3000
