apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public-ip-pool
  namespace: metallb-system
spec:
  addresses:
    - 13.235.16.238/32   # ðŸ‘ˆ your public IP

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: public-ip-advert
  namespace: metallb-system
spec:
  ipAddressPools:
    - public-ip-pool
